version: "3"

networks:
  web:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - tmp-data:/app/tmp
    depends_on:
      - web
    networks:
      - default
      - web

  web:
    build: ./api
    container_name: rails
    command: puma -b unix:/app/tmp/sockets/puma.sock
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
      - tmp-data:/app/tmp
    tty: true
    stdin_open: true
    networks:
      - default
      - web

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - "3002:3002"
    tty: true
    stdin_open: true
    command: npm run dev
    networks:
      - default
      - web
volumes:
  mysql_data:
  bundle:
  tmp-data:
